### ISSUE TITLE
Handle paid overtime

### ISSUE THREAD

**Issue by terotil** [SC5/harvestbalance-chrome#1]
Paid overtime should not be included in hour balance.  I've got no idea how this could be handled.

**Comment by mpuittinen** [comment]
If that cannot be solved automatically, one option is to add a manually managed “Balance correction” field to the settings of the plug-in.

**Comment by hoppula** [comment]
Easy way would be to have a list of keywords, e.g. ["ylityö","overtime"] and check for matches in day_entry.notes. If notes.match(/keyword/) returns non-falsy value, it shouldn't be included in totals.
This list could be editable in extension settings panel, so anyone would be free to use whatever keywords they wish. What do you think?

**Comment by hoppula** [comment]
After discussing this with @terotil we decided that it's best to implement the feature as "Balance correction" as @mpuittinen suggested. We're going to have a list of balance corrections, user can input description & amount. This way you can add corrections for projects that are already closed and uneditable. We also decided that there needs to be a setting for initial balance.

**Comment by mpuittinen** [comment]
Where would the balance corrections be stored / managed? In one time reporting solution that I was involved in building (for CRF Health and for Kronodoc internal use), we had freeze points (e.g. end of month) for balances and the “current” balance was calculated based on the latest freeze point + hours reported after that. Would it be feasible to have those freeze points (with adjustments) in Harvester and have the Chrome plug-in query the latest balance from Harvester and latest hours reports from Harvest? Freezing the balances would be a monthly admin task (manual).

**Comment by hoppula** [comment]
I wouldn't want to introduce any external dependencies here, so I'm thinking they'd be in the same IndexedDB/LocalStorage as other settings. But we can add export as .json or something so they'd be easy to backup.

And yeah, it makes more sense to have month instead of description as other field, that way we can reduce harvest balances and paid overtimes from any given point and we only need one "freeze point", the initial balance.

**Comment by hoppula** [comment]
This has now been implemented as discussed, check latest version and give feedback if you have ideas for better implementation :) Export to .json still missing though.
